AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for a basic transit tracking service
Parameters:
    TransitCollectorDynamoDbTableName:
        Type: String
        Description: Enter the DynamoDB table name.
    LambdaName:
        Type: String
        Description: Enter the Lambda name.
Resources:
    TransitCollectorLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                ZipFile: ./deploy/lambda.zip
            Description: Lambda for a basic transit tracking service
            Environment:
                Variables:
                    CTA_BUS_API_KEY: pass
                    CTA_BUS_PREDICTION_ROUTE: pass
                    CTA_BUS_STOP_ID: pass
                    DYNAMODB_TABLE:
                        Ref: TransitCollectorDynamoDbTableName
            FunctionName:
                Ref: LambdaName
            Handler: lambda_handler
            Role: arn:aws:iam::421713074241:role/cta-bustracker-lambda
            Runtime: python2.7
            Timeout: 10
