AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for a basic transit tracking service
Parameters:
    CtaBusPredictionRoute:
        Type: String
        Description: CTA bus prediction route.
    CtaBusApiKey:
        Type: String
        Description: CTA bus API key.
    CtaBusStopId:
        Type: String
        Description: CTA bus stop ID.
    LambdaName:
        Type: String
        Description: Enter the Lambda name.
    TransitCollectorDynamoDbTableName:
        Type: String
        Description: Enter the DynamoDB table name.
Resources:
    TransitCollectorLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                ZipFile: ./deploy/lambda.zip
            Description: Lambda for a basic transit tracking service
            Environment:
                Variables:
                    CTA_BUS_API_KEY:
                        Ref: CtaBusApiKey
                    CTA_BUS_PREDICTION_ROUTE:
                        Ref: CtaBusPredictionRoute
                    CTA_BUS_STOP_ID:
                        Ref: CtaBusStopId
                    DYNAMODB_TABLE:
                        Ref: TransitCollectorDynamoDbTableName
            FunctionName:
                Ref: LambdaName
            Handler: main.lambda_handler
            Role: arn:aws:iam::421713074241:role/cta-bustracker-lambda
            Runtime: python2.7
            Timeout: 10
