AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for a basic transit tracking service
Parameters:
    TransitCollectorDynamoDbTableName:
        Type: String
        Description: Enter the DynamoDB table name.
    TransitCollectorLambdaBucketName:
        Type: String
        Description: Enter the S3 bucket name.
Resources:
    TransitCollectorDynamoDbTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions:
                - AttributeName: stop_id
                  AttributeType: S
                - AttributeName: current_time
                  AttributeType: N
            KeySchema:
                - AttributeName: stop_id
                  KeyType: HASH
                - AttributeName: current_time
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TableName:
                Ref: TransitCollectorDynamoDbTableName
    TransitCollectorLambdaBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName:
                Ref: TransitCollectorLambdaBucketName
