- name: provision all transit-collector stacks
  hosts: localhost
  connection: local
  tasks:
    - name: "launch CTA bustracker collector base resources"
      cloudformation:
          stack_name: "coco-cta-bustracker-collector"
          state: "present"
          region: "us-east-1"
          template: "cloudformation-base-stack.yml"
          template_parameters:
              TransitCollectorDynamoDbTableName: "coco_cta_bustracker"
          tags:
              Stack: "coco-cta-bustracker-collector"
    - name: "Prep Lambda Deploy Package"
      command: "./prep-lambda-deploy.sh"
    - name: "launch CTA bustracker Lambda function"
      cloudformation:
          stack_name: "coco-cta-bustracker-collector"
          region: "us-east-1"
          template: "cloudformation-lambda-stack.yml"
          template_parameters:
              TransitCollectorDynamoDbTableName: "coco_cta_bustracker"
              LambdaName: "coco_cta_bustracker"
          tags:
              Stack: "coco-cta-bustracker-collector"
